os: linux 
files:
  - source: /
    destination: /var/www/html/
  hooks:
  ApplicationStop: 
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
